name: Deploy to Fly.io and Koyeb

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Koyeb CLI
        uses: koyeb/actions@v1
        with:
          version: latest

      - name: Deploy to Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: koyeb service redeploy gentle-maryann/discord-roast --token "$KOYEB_TOKEN" --app roaster-bot
